### ISSUE TITLE
Fix the Readme.md file so that is a full description of this task

### ISSUE THREAD

**Issue by HowardCohl** [joonbang/case-conversion#1]
@joonbang I think it is missing some description.

Please give the full calling sequence for instance, and make sure the description is fully correct.

**Comment by joonbang** [comment]
The Readme.md file should now be more descriptive and clear as to what the program does.

**Comment by HowardCohl** [comment]
You need to include examples of the calling sequence for the program for when it does the mM task and for when it does the azAZ task.

**Comment by joonbang** [comment]
What do you mean by calling sequence?

**Comment by HowardCohl** [comment]
@joonbang Have a look here:

https://github.com/kevinshen100/NIST-Practice-Tasks

Did you do the codeacademy command line course?

**Comment by joonbang** [comment]
Yes, I completed the codeacademy course.
